"""True device sample-rate measurement, distinct from the app's own
poll/render-loop rate.

SPEC-ui-setup-task-selection.md S24: the Operator Panel's existing "FPS"
label counts how often the app's own ``QTimer`` loop ticks (driven by
``configs/default.yaml``'s ``app.target_fps``), not how often a *new* gaze
sample actually arrives from the tracker. When the poll loop runs faster
than the device delivers new samples (e.g. polling at 150 while a GP3 HD
on a USB 2.0 port is capped at 60 Hz), most poll ticks just re-read the
same stale sample -- FPS reads normally, but real sample throughput does
not. This tracker measures the latter, from the same per-sample capture
timestamp (``GazeSample.t_ns``) already stamped once per socket receive
event by ``GazepointClient._run_socket``, never regenerated by
``latest()``.
"""

from __future__ import annotations

_WINDOW_NS = 1_000_000_000


class SampleRateTracker:
    """Rolling 1-second measurement of the rate of *distinct* incoming
    samples, keyed off each sample's own capture timestamp rather than how
    often the caller happens to poll."""

    def __init__(self) -> None:
        self._last_sample_t_ns: int | None = None
        self._new_sample_count = 0
        self._window_start_ns: int | None = None
        self._rate_hz: float | None = None

    @property
    def rate_hz(self) -> float | None:
        """The most recently completed 1-second window's rate, or ``None``
        before the first window has completed."""
        return self._rate_hz

    def update(self, sample_t_ns: int, now_ns: int) -> None:
        """Record one (sample capture time, now) observation.

        Call once per poll, even when the sample hasn't changed since the
        last call -- only a capture-timestamp change counts toward the
        rate, so repeated calls with the same ``sample_t_ns`` (a poll
        loop outrunning the device) correctly contribute nothing.
        """
        if self._window_start_ns is None:
            self._window_start_ns = now_ns
        if self._last_sample_t_ns is not None and sample_t_ns != self._last_sample_t_ns:
            self._new_sample_count += 1
        self._last_sample_t_ns = sample_t_ns

        elapsed_ns = now_ns - self._window_start_ns
        if elapsed_ns >= _WINDOW_NS:
            self._rate_hz = self._new_sample_count * 1e9 / elapsed_ns
            self._new_sample_count = 0
            self._window_start_ns = now_ns
